### PR TITLE
Replace all this.Cc/this.Ci with Cc/Ci

### PR DESCRIPTION
**Pull request by ath0mas**

### CODE REVIEW

**Comment by ath0mas** [comment]
Seems not that good
`Cc is not defined - utility.js:53:0` opening Preferences
`ReferenceError: Cc is not defined - utility.js:47:9` changing Application mode

**Comment by YoruNoHikage** [comment]
I don't know what makes Cc defined or not.
Try this at the top : 
`const { classes: Cc, interfaces: Ci, utils: Cu } = Components;`

**Comment by ath0mas** [comment]
Same for me ^^
Cc and Ci are defined at the end of EchofonCommon object in utility.js...
Are you able to debug/add breakpoints through Browser Toolbox? It does not stop on breakpoint for echofon for me :(

I'll check each use of Cc/Ci/this.Cc/this.Ci by hand later this week-end

**Comment by YoruNoHikage** [comment]
It doesn't work either, I just use some `console.log`. :/

**Comment by ath0mas** [comment]
I mistakenly deleted my branch, so PR was closed
No matter. Branch restored. I'll check uses and give feedback later ;)

**Pull request closed without merging**
